### ISSUE TITLE
Taskbar active selection color

### ISSUE THREAD

**Issue by Cory-Watson** [Zren/breeze-alphablack#10]
First off, this is truly one of the best plasma themes I have ever seen! Great work!

Do you know how I could change the color of the active selection in the taskbar? More specifically, I guess one could say it's an issue with the active selection of any applet in the panel because the systray and the application menu have the same behavior.
 
![taskbar_active_selection_color](https://user-images.githubusercontent.com/46908765/53688022-03d90680-3d0b-11e9-8b78-80cf7b82adb2.png)

**Comment by Cory-Watson** [comment]
I would be more than happy to provide a pull request, just haven't came across an effective way to fix this yet...

**Comment by Cory-Watson** [comment]
Closing issue, I just manually changed the `DecorationFocus` color values in the `.local/share/plasma/desktoptheme/breeze-alphablack/colors` file.

**Comment by Zren** [comment]
The tasks in the taskmanager widget use https://github.com/Zren/breeze-alphablack/blob/master/widgets/tasks.svg

If you look at the svg's text, you'll notice the `focus-` elements use the `class="ColorScheme-ButtonFocus"`  + `style="fill:currentColor"` to draw the color of those lines.

https://github.com/Zren/breeze-alphablack/blob/master/widgets/tasks.svg?short_path=6c8cc3e#L77

If we look at Plasma's code, `ButtonFocus` is generated using `%buttonfocuscolor` which is generated using `color(Theme::FocusColor, Theme::ButtonColorGroup)`

* https://github.com/KDE/plasma-framework/blob/9fc663d9f0edf41acd098b7c6c7b090d2c7b5aea/src/plasma/private/theme_p.cpp#L553
* https://github.com/KDE/plasma-framework/blob/9fc663d9f0edf41acd098b7c6c7b090d2c7b5aea/src/plasma/private/theme_p.cpp#L465

The `color(...)` function tells us it uses `scheme->decoration(KColorScheme::FocusColor)` where `scheme = &buttonColorScheme`.

https://github.com/KDE/plasma-framework/blob/9fc663d9f0edf41acd098b7c6c7b090d2c7b5aea/src/plasma/private/theme_p.cpp#L678

So we need to edit `[Colors:Button] DecorationFocus=30,146,255` in the `colors` file.

https://github.com/Zren/breeze-alphablack/blob/master/colors#L24

I should note, `sethighlightcolor.py` essentially calls `_applyColors(...)` in `desktoptheme.py`. It uses that single `highlightColor` to generate a `focusColor` using `focusColor = hoverEffect(highlightColor, -31, -28, 25)` which lowers the red + green, and adds some blue.

* https://github.com/Zren/breeze-alphablack/blob/master/desktoptheme.py#L322
* https://github.com/Zren/breeze-alphablack/blob/master/desktoptheme.py#L367

*issue was closed* ... Well, now you know how it works.

**Comment by Cory-Watson** [comment]
Awesome! Thanks for the Plasma crash course!
