### ISSUE TITLE
Change panel opacity status according to applications?

### ISSUE THREAD

**Issue by roachsinai** [Zren/breeze-alphablack#12]
I have set `panel opacity` to zero. Like I'm using `Vim` and press `F11` to fullscreen, and after I use `Alt+Tab` change to `Chrome`, my panel fixed not chage to transparent.

The expected behavior is `panel` could be transparent when I change to other application meas `panel opacity` status should be fit to the focused application, right?

**Comment by Zren** [comment]
Screenshot of before and after?

**Comment by roachsinai** [comment]
panel+vim(focused, without fullscreen)

![image](https://user-images.githubusercontent.com/9500049/54105011-ac265380-440c-11e9-871e-ce26bd6667f5.png)

**Comment by roachsinai** [comment]
panel+vim(fullscreen)+chrome(focused, without fullscreed)

![image](https://user-images.githubusercontent.com/9500049/54105031-bfd1ba00-440c-11e9-8d94-d349d2895c64.png)

**Comment by roachsinai** [comment]
panel+chrome(fullscreen)+vim(focused, without fullscreed)

![image](https://user-images.githubusercontent.com/9500049/54105116-0cb59080-440d-11e9-9270-a13d5da9d175.png)

**Comment by Zren** [comment]
Oh, your "bug" is that a fullscreen window which normall covers the panel, is now below the panel when you alt tabbed to another window? ... that's not a bug with the desktop theme tbh.

If you want your panel to not be transparent when a window is touching the panel, use Latte Dock which supports that feature.

**Comment by roachsinai** [comment]
Got it...emmm, 

> fullscreen window which normally covers the panel

Should the fullscreen window still cover the panel after I alt tabbed to another window?

**Comment by Zren** [comment]
Fullscreen windows are just normal windows that completely cover your screen. When they're focuses, the panel is drawn underneath the window, but when it's not in focus, the panel is drawn overtop the fullscreen window. The panel isn't really designed to be transparent, unless you have the "become solid color when a window touches it".

**Comment by roachsinai** [comment]
Thanks for your explanation!!!
