### ISSUE TITLE
Transparent widgets after qt-5.12.2 update

### ISSUE THREAD

**Issue by r0skar** [Zren/breeze-alphablack#13]
FYI there has been a problem with the most recent qt update and the default breeze dark plasma theme. Using the `breeze-alphablack` theme, I experience the same issue as mentioned in the reports below.

Relevant links:
https://bugs.kde.org/show_bug.cgi?id=405548
https://phabricator.kde.org/D19821

**Comment by Zren** [comment]
Ah good point. The template dialogs/background doesn't have `type="text/css"`. I think I'll add that attribute to the style tag instead of removing the tag altogether like the kde patch.

https://raw.githubusercontent.com/Zren/breeze-alphablack/master/_templates/dialogs/background.svg

**Comment by Zren** [comment]
1. Copy the [`_templates/dialogs/background.svg`](https://raw.githubusercontent.com/Zren/breeze-alphablack/master/_templates/dialogs/background.svg) to `~/.local/share/plasma/desktoptheme/breeze-alphablack/`
2. Change the dialog opacity to re-render the svg + refresh.

Is it fixed?

**Comment by r0skar** [comment]
Works great. Thanks a lot for the quick response and fix - awesome work!

**Comment by roachsinai** [comment]
So release `V15` should fix this issue?

**Comment by roachsinai** [comment]
It fixed, sorry to bother.
