### ISSUE TITLE
HOW TO disable highlight color on kmenu and system tray

### ISSUE THREAD

**Issue by manuelLandreau** [Zren/breeze-alphablack#15]
Hi! 
Best KDE theme so I'm frustrated to not be able to disable highlight color on kmenu and system tray, I think it doesn't fit with the panel, but keeping highlight color on the task manager of course (skuse my english).

Which variable can i use to disable it or hide it ? I barely understand Qt :(

PS kmenu icon are never the same size of the app launcher icons on any theme.. strange..

**Comment by Zren** [comment]
The `widgets/tabbar.svg` is what is used to draw the line avoe the menu, system tray, and any opened widgets.

* `/.local/share/plasma/desktoptheme/breeze-alphablack/widgets/tabbar.svg`

Normally when you delete an svg in the plasma desktop theme, it would inherit the default theme's svg (`/usr/share/plasma/desktoptheme/default/`), however the code that draws `tabbar.svg` is a special case and will only draw it if it's part of the current theme.

More info on plasma themes at: https://techbase.kde.org/Development/Tutorials/Plasma5/ThemeDetails
