### ISSUE TITLE
Transparent menubar menus

### ISSUE THREAD

**Issue by zilrich** [Zren/breeze-alphablack#16]
Hello, I'm having an issue where the menu bar menus (I haven't noticed this on any other elements) are completely transparent + blur. This results in readability issue when the background is light, like on the attached screenshot. I'm not sure if this is an error on my part is some way, if so please let me know!
![Screenshot_20190503_164631](https://user-images.githubusercontent.com/47159471/57145534-b1c46800-6dc3-11e9-99f5-8d6ea4bd2784.png)

**Comment by Zren** [comment]
What application style > widget style are you using? What color theme are you using?

**Comment by Zren** [comment]
Wouldn't this also affect the breeze dark "desktop theme" as well?

**Comment by zilrich** [comment]
Yeah sorry. This was a setting in the widget style. I'll close the issue.
