### ISSUE TITLE
Widget not working on 5.18

### ISSUE THREAD

**Issue by twifty** [Zren/breeze-alphablack#18]
Been using this theme for over 2 years, but when I went to use the widget today it destroyed my systems appearance.

None of the buttons/sliders/picker works in the widget. All initial values seem to be set to a default (3 colors are #000, 3 sliders at 90%). Changing values and clicking "Apply Colors" will apply only colors but not opacity... Reset colors/defaults have no effect.

Additionaly, the readme says running `python3 desktoptheme.py` will list commands, however nothing is output. Any command using `desktoptheme.py` just doesn't work. I've managed to somewhat restore my system using the `set*.py` set of scripts, which do work.

Operating System: Manjaro Linux 
KDE Plasma Version: 5.18.4
KDE Frameworks Version: 5.68.0
Qt Version: 5.14.2
Kernel Version: 5.4.31-1-MANJARO

I'm using the current versions available on the KDE store. I don't mind cloning the source and installing that. How do you recommend using the source? I guess I can link the package into `~/.local/share/plasma/desktoptheme` but what about the widget?

**Comment by Zren** [comment]
I'm using Manjaro too. 

```bash
$ kreadconfig5 --file="$HOME/.local/share/plasma/desktoptheme/breeze-alphablack/metadata.desktop" --group="Desktop Entry" --key="X-KDE-PluginInfo-Version"
16

$ kreadconfig5 --file="$HOME/.local/share/plasma/plasmoids/com.github.zren.alphablackcontrol/metadata.desktop" --group="Desktop Entry" --key="X-KDE-PluginInfo-Version"
6
```

```
$ python3 ~/.local/share/plasma/desktoptheme/breeze-alphablack/desktoptheme.py getall
dialog.opacity: 0.9
dialog.padding: 2
panel.opacity: 0.9
panel.padding: 2
panel.taskStyle: inside
theme.accentColor: 32,33,36
theme.highlightColor: 22,160,133
theme.textColor: 239,240,241
widget.opacity: 0.7

$ python3 ~/.local/share/plasma/desktoptheme/breeze-alphablack/desktoptheme.py set theme.highlightColor 255,0,0
```

**Comment by Zren** [comment]
Make sure you've updated the `breeze-alphablack` Plasma/Desktop Theme. It sounds like you've only updated the AlphaBlack Control widget.

**Comment by twifty** [comment]
@Zren I made sure to update both the theme and the widget when I saw there was a problem. That reminds me, please include a `.version` file or something similar in each.

I used the `set__.py` scripts myself to fix the styling issues. I know the theme itself is working, it's just the widget that appears to not be communicating properly.

**Comment by Zren** [comment]
> please include a `.version` file

That's what the `metadata.desktop` file is... I just commented with commands to read just the version, but you could also just cat those files...

https://store.kde.org/p/1084931/ has `breeze-alphablack-v16.zip` uploaded `2020-03-16`.

**Comment by twifty** [comment]
Fixed it. For some reason installing via "Add Widget" yesterday installed version 15. I just downloaded the zip from store.kde.org and overwrote existing. `desktoptheme.py` now appears to work. However, the widget is still not working correctly. Let me try to investigate a little more.

**Comment by Zren** [comment]
Reload plasma. The widget runs "getall" at the beginning to read all the properties, and it likely errored as you had v15 installed when it loaded.

**Comment by twifty** [comment]
That worked. Perhaps you could add a version checker to the widget. Had I know the two parts were out of sync, version wise, I could have fixed it sooner. :-)
