### ISSUE TITLE
How to set window decoration colors using new desktoptheme.py [Able to do it using the desktop widget] 

### ISSUE THREAD

**Issue by ableabhinav** [Zren/breeze-alphablack#19]
I ran `python3 ~/.local/share/plasma/desktoptheme/breeze-alphablack/desktoptheme.py getall` but there does not seem to be an option for window decorations. 
Furthermore, the Readme doesn't seem to be updated after moving all commands to desktoptheme.py
Kindly make the changes
Edit: Was able to do it using the desktop widget

**Comment by Zren** [comment]
Ah good point. I updated the description on KDE Store, but forgot the ReadMe.

If you run `set theme.accentColor 0,0,0` it will change the panel and the window decorations. I can add a dedicated function for changing the window decorations if that's not what you're after, though you can edit `~/.config/kdeglobals` too.

```
python3 ~/.local/share/plasma/desktoptheme/breeze-alphablack/desktoptheme.py set theme.accentColor 0,0,0
```
