### ISSUE TITLE
Hover box color mismatch, text readability problem

### ISSUE THREAD

**Issue by r-o-o-t-y** [Zren/breeze-alphablack#2]
Hey first of all I wanna say LOVE the theme, especially now with the new blur effect

Now, I have the following problem, I usually use the theme at 85% opacity and I've noticed that when I hover over my tray icons, the readability of the subtitle is a lot worse than that of the main title:
![screenshot_20180714_141557](https://user-images.githubusercontent.com/36138721/42724403-d45413d6-8771-11e8-940b-0577c1f50a0a.png)

Compare this to breath in manjaro (the original breeze dark doesn't have much going for it in the way of transparency):
![screenshot_20180714_141643](https://user-images.githubusercontent.com/36138721/42724408-f2787a8c-8771-11e8-9c48-a25120c1956f.png)

I've also noticed that the hover boxes pick colors/blur entirely independent of the panel itself:
![screenshot_20180714_142539](https://user-images.githubusercontent.com/36138721/42724411-04748186-8772-11e8-9c3a-975e28d6b3d3.png)

And that the readability problem becomes huge if the opacity is set to 0%, present in both the hover boxes and the panel popups, and this happens regardless of the color scheme selected in the KDE system settings:
![screenshot_20180714_142521](https://user-images.githubusercontent.com/36138721/42724445-8bae19f0-8772-11e8-945e-6bfbffe8a756.png)

The theme seems to set the font colors in the panel independently of Plasma already, so is it possible for it to set colors that adapt to the shift in opacity (white on black, black on white etc.)? And also to make the hover boxes match the panel popups (an extra toggle?)?

**Comment by RaitaroH** [comment]
If you ask me, the theme will have to take in consideration what you have behind the menus at all times because that is the factor. Take your example, looks terrible when you have a white page behind, but open up something dark and the event calendar looks just fine. 

Basically what you want is for the theme to automatically change akin to [Latte Dock](https://youtu.be/dQk7eKcMRkU?t=2m29s). As you can see it is totally possible to achieve this. Latte also has Dynamic Background which appears just before this.

I even tried to increase the blur and noise in the Effects Settings for Blur but it only helps a little.

**Comment by Zren** [comment]
Desktop Themes can't dynamically change like Latte Dock can.

There's the "Background Contrast" Desktop Effect which might help. Probably won't.

The default opacity is 0.9 (aka 90%) for a reason. You don't want too much transparency, but we do want the stuff behind the popup to "texture" the background so it's not a solid black background.

Various widgets/tooltips use 70% opacity text to "lerp" a "lighter" text color.

**Comment by RaitaroH** [comment]
@Zren I suppose Latte is just checking on the background itself and not behind it. It is close to impossible and pointless anyway. I just recommend to close the issue.

**Comment by Zren** [comment]
I added the ability to change the panel/widget/titlebar text color, which should be enough to close this. While the widget can set 100% transparent popups, it's not recommended.

![](https://i.imgur.com/60ck2rT.png)

Will be in v13 of the desktoptheme + v4 of the widget, whenever I release it tonight/tomorrow.
