### ISSUE TITLE
Clarification on altering color values

### ISSUE THREAD

**Issue by wsdfhjxc** [Zren/breeze-alphablack#20]
To be more precise, I'm curious about [this particular](https://github.com/Zren/breeze-alphablack/blob/5143d3ff0027fc13fd863795e36ca38196eb3569/desktoptheme.py#L590) line.

There must have been some reason for doing that, and I can see that the picked highlight color is displayed correctly for items in the default Plasma's Task Manager plasmoid. However, the modified highlight color (not the original one) seems to be present in many other places, for example in KRunner or in the Add Widgets panel. Depending on the picked highlight color value, the modified color might be slightly different, or very different from the picked one (e.g. picked red, but modified is purple).

This seems like a bug, as there is a mismatch between what the user picks, and what is displayed.

After zero-ing the RGB arguments in the `hoverEffect` method call, the picked color is preserved correctly.

**Comment by Zren** [comment]
* https://github.com/Zren/breeze-alphablack/blame/5143d3ff0027fc13fd863795e36ca38196eb3569/desktoptheme.py#L590
* https://github.com/Zren/breeze-alphablack/commit/e8b522f6209ae734306012ed845550182764b958#diff-72e2daccbcb753ebd35947d0550e078c327470ab2d8a6878ccbe96d60a818f2bR322

It appears to set the `DecorationFocus` in all color groups.

`DecorationFocus=30,146,255` is the `[Colors:Complementary]` that `breeze-dark` used to use:

* https://github.com/KDE/plasma-framework/commit/fb8f02de76d58a14ff6bf4fc8501b0d44abd3721#diff-27593986a702ab9c58d8c00adc097f888c3084f5812d6b519f2aa5a349e2e593L94

Doesn't look like it's used now though:

* https://github.com/KDE/plasma-framework/blame/master/src/desktoptheme/breeze-light/colors#L30
* https://github.com/KDE/plasma-framework/blame/master/src/desktoptheme/breeze-dark/colors#L30

**Comment by wsdfhjxc** [comment]
Ok, so this is specific to the Breeze's blue highlight color, and it used to make sense to modify the RGB values to match its variant. The issue here is that, this code unconditionally modifies the RGB values of any provided color, e.g. turning red into purple.

I suggest to add some conditionals, or just throw away the `-31, -28, 25` arguments for that method call, so there are no more misleading color modifications, and the picked color will be used explicitly as is. What do you think about that?

**Comment by Zren** [comment]
Can you provide a screenshot of what specifically that color controls?

**Comment by wsdfhjxc** [comment]
![plasmoid](https://user-images.githubusercontent.com/20323160/101432867-f43c1800-3909-11eb-88b3-c934b07fd2f6.png)

![krunner](https://user-images.githubusercontent.com/20323160/101432894-fb632600-3909-11eb-86f2-e91d1a49cb45.png)

![widgets](https://user-images.githubusercontent.com/20323160/101432903-0027da00-390a-11eb-9741-db8f7ad4fed9.png)

---

As you can see, some elements (sliders, pin button) use the actually picked color (`#926262`), while others (focused text fields, KRunner items, Add Widgets panel items) use the modified, purplish version of it. The Plasma's Task Manager plasmoid is fine.

I think that elements in the focused state are affected, as the modified highlight color is assigned to the `focusColor` property, but in some places the `focusColor` property isn't used, but `selectionColor` is, as the unmodified color is assigned to that property. Either way, there is a mismatch between what the user picks, and what is displayed, and it makes me sad to see that :slightly_smiling_face: .

To quickly test the suggested fix, you can check out [a branch](https://github.com/wsdfhjxc/breeze-alphablack/tree/colors-fix) from my testing fork, if you wish so.

**Comment by Zren** [comment]
Ah, `#926262` is a perfect example thank you.

It looks like `-31, -28, 25` was only used for the `Complementary` color. Are you okay with that purple color being generated for Complementary colors and using highlightColor for the rest?

**Comment by Zren** [comment]
Or should I use `deltaColor(accentColor, 32)`?

**Comment by wsdfhjxc** [comment]
I think I'm fine with your recent changes, as I can no longer see the purple color, so that's terrific.

Thank you for your time, and for the hard work on all these numerous Plasma-related tools and additions.
