### ISSUE TITLE
Titlebar colours not applying to gtk apps

### ISSUE THREAD

**Issue by mmcnutt** [Zren/breeze-alphablack#22]
I've noticed since updating to plasma 5.20 that gtk apps are not getting the colours applied through AlphaBlack control widget.

Is present on the latest version 18 and the previous build

Fedora 33 KDE, Plasma 5.20.4, Frameworks 5.77, breeze-gtk packages installed

**Comment by ryu-ketsueki** [comment]
If I'm not mistaken, the Breeze GTK is designed to use the colors from the color scheme being used by Plasma, so you would need to modify the color scheme on System Settings. It wasn't designed to use the colors applied by AlphaBlack.

**Comment by mmcnutt** [comment]
This is true for some gtk windows but not others - things like Lutris, chromium and firefox for instance do not

previous version of alphablack definitely applied colours to these apps

previously

![image](https://user-images.githubusercontent.com/17693819/103274608-cc723880-4a0d-11eb-8f62-fc1db384f70f.png)

**Comment by mmcnutt** [comment]
appears to be working again correctly in 5.21
