### ISSUE TITLE
Transparent widgets (with blur)

### ISSUE THREAD

**Issue by RaitaroH** [Zren/breeze-alphablack#4]
I know the theme allows a transparent panel, but I would like to have the option to make the widgets transparent too. I noticed that plasma allows rgb and not rgba so I am not sure where to look to allow transparency for the widgets. Somebody did make a breeze dark transparent theme so I know is possible, but I like this theme a lot more.

**Comment by Zren** [comment]
As in... transparent widget backgrounds?

Use the `setwidgetopacity.py` script, or the AlphaBlack Control widget (https://www.opendesktop.org/p/1237963/).

```
python3 ~/.local/share/plasma/desktoptheme/breeze-alphablack/setwidgetopacity.py 0.4
```

**Comment by RaitaroH** [comment]
Hmmm, is not there. 
`python3: can't open file '/home/raitaro/.local/share/plasma/desktoptheme/breeze-alphablack/setwidgetopacity.py': [Errno 2] No such file or directory`

Let me reinstall the theme... Yeah so after a reinstall the script appeared. But 2 days ago it wasn't :thinking:  

Anyway, thank you for the awesome theme.

**Comment by RaitaroH** [comment]
Oh yeah, and if you don't have the script the widget you mentioned doesn't do anything because it is relying on those scripts. I guess because I had this theme forever something went wrong with the update maybe.

**Comment by RaitaroH** [comment]
@Zren I can also say that there might be a bug in the script or something.

![peek 2018-08-24 18-08](https://user-images.githubusercontent.com/19552720/44592388-0b05e180-a7c9-11e8-8325-bf21d37dede6.gif)

![peek 2018-08-24 18-15](https://user-images.githubusercontent.com/19552720/44592593-b6af3180-a7c9-11e8-9122-10cc318fa4fa.gif)

A plasma restart does not help either. I have to change the desktop theme, remove alphablack, reinstall it and now it works. A bit weird.

**Comment by Zren** [comment]
The **desktop** widget opacity changes. https://www.youtube.com/watch?v=t0rYH2lN5w0

You didn't test the panel or "panel popup" opacity.

Also, you only need to click "Apply Colors" if you want to change the Breeze Window Decoration color (aka titlebars).

**Comment by RaitaroH** [comment]
@Zren Ah, I see. But for some reason the .9 in the first image and .9 in the second are quite different levels of transparency there though. Anyway thank you.
