### ISSUE TITLE
Choose player

### ISSUE THREAD

**Issue by RaitaroH** [Zren/breeze-alphablack#5]
![peek 2018-08-24 18-29](https://user-images.githubusercontent.com/19552720/44593397-e65f3900-a7cb-11e8-82bf-d19e60be3a91.gif)

Can this be fixed? I know in the default breeze dark theme it is not fixed.

**Comment by Zren** [comment]
That's a bug with... either Plasma or Breeze.

Actually, it's probably a bug in Breeze Dark.

![](https://i.imgur.com/ccC490D.png)

As it seems to be fine in the Breeze [Light] color theme.

![](https://i.imgur.com/0aKhW7e.png)

You can test other black/dark desktop themes, and you'll notice they have the same bug.

**Comment by RaitaroH** [comment]
I did mention it appears in the default dark theme. I was just wondering if they might have forgotten to theme it. So it is a plasma issue huh... bummer. I need to open an issue again.
